
SAMPLE_TIME = 'SAMPLE_TIME'
SUBTITLE_AI_MODE = 'SUBTITLE_AI_MODE'
REMOTE_ADDRESS = 'REMOTE_ADDRESS'
SUBTITLE_INPUT_DEVICE = 'SUBTITLE_INPUT_DEVICE'
S2T_MODEL_SIZE = 'S2T_MODEL_SIZE'
S2T_LANGUAGE='S2T_LANGUAGE'
