
SAMPLE_TIME = 'SAMPLE_TIME'
SUBTITLE_AI_MODE = 'SUBTITLE_AI_MODE'
REMOTE_ADDRESS = 'REMOTE_ADDRESS'
SUBTITLE_INPUT_DEVICE = 'SUBTITLE_INPUT_DEVICE'
S2T_MODEL_SIZE = 'S2T_MODEL_SIZE'
S2T_LANGUAGE='S2T_LANGUAGE'


OPENAI_API_BASE = 'OPENAI_API_BASE'
OPENAI_API_KEY = 'OPENAI_API_KEY'
GPT_CONTEXT_CNT = 'GPT_CONTEXT_CNT'
GPT_SPEAK_SPEED = 'GPT_SPEAK_SPEED'
GPT_S2T_MODE = 'GPT_S2T_MODE'
GPT_T2S_MODE = 'GPT_T2S_MODE'
GPT_S2T_REMOTE_ADDRESS = 'GPT_S2T_REMOTE_ADDRESS'
GPT_T2S_REMOTE_ADDRESS = 'GPT_T2S_REMOTE_ADDRESS'
GPT_SYSTEM_CMD = 'GPT_SYSTEM_CMD'